name: Build and Deploy

on: push

env:
  AWS_S3_BUCKET: inquests-ca-lambda
  AWS_LAMBDA_FUNCTION: 'InquestCrud'
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build project
        run: |
          npm ci
          npx tsc --build tsconfig.json

      - name: Create zip deployment package
        run: |
          cd ./build
          zip -r ../build.zip . ../node_modules ../ormconfig.js

      - name: Copy zip deployment package to AWS S3
        run: |
          aws s3 cp build.zip s3://${{ env.AWS_S3_BUCKET }}

      - name: Publish Lambda function
        run: >
          aws lambda update-function-code
          --s3-bucket ${{ env.AWS_S3_BUCKET }}
          --s3-key build.zip
          --function-name ${{ env.AWS_LAMBDA_FUNCTION }}
          --publish
